name: Automation
on:
  push:
    branches: ['**']
    tags: ['**']
  pull_request:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: TTest
        run: npm run ci:test
